// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-hero/VariantA.tsx": () => import("../components/mockups/home-hero/VariantA.tsx"),
  "./components/mockups/home-hero/VariantB.tsx": () => import("../components/mockups/home-hero/VariantB.tsx"),
  "./components/mockups/admin-locations/DrillIn.tsx": () => import("../components/mockups/admin-locations/DrillIn.tsx"),
  "./components/mockups/admin-locations/OpsDashboard.tsx": () => import("../components/mockups/admin-locations/OpsDashboard.tsx")
};
